name: grid_ai
channels:
  - pytorch
  - nvidia
  - pyg
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - scikit-learn=1.2.2
  - jupyterlab
  - pytorch=2.1.0
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - pyg
  - cudatoolkit=11.8
  - pip:
    - tqdm
    - PyYAML
    - pandapower
    - torch-geometric
