# Configuration for case 9241 pegase
# Updated to load directly from pandapower.networks

log_dir: logs/simulation_case_9241 # Directory for log files

pandapower_module: pandapower.networks.case9241pegase # Loads the network function directly

contingency_file: data/contingencies/contingencies_9241.txt # Path to the contingency list
output_dir: data/raw/case_9241/ # Directory to save simulation results

simulation:
  method: ac # Power flow method (ac or dc)
  # Optional: Add contingencies_per_task if planning parallel runs
  # contingencies_per_task: 200
