# Preprocessing configuration for Grid Security AI
log_dir: "logs/preprocessing"
raw_simulation_dirs: 
  - "data/raw/simulation_results"
  - "data/raw/case_1354_small"
  - "data/raw/test_simulation"
processed_dataset_file: "data/processed/full_dataset.pt"
normalization_params_file: "data/processed/normalization.pt"

# Grid configuration
pandapower_module: "pandapower.networks.case1354pegase"  # Using case1354 as base

# Preprocessing parameters
chunk_size: 1000  # Number of files to process in memory at once